#!/usr/bin/env python

from string import ascii_letters, digits
from random import SystemRandom
from crypt import crypt
from getpass import getpass

allowed_salt_characters = ascii_letters + digits + './'
salt_length = 16

secure_random = SystemRandom()
salt = ''.join(secure_random.choice(ascii_letters + digits + './') for x in range(salt_length))

print "Please enter the password or passphrase you'd like to use for your email account."
password = getpass()
crypt = crypt(password, "$6$" + salt)

print
print 'Here is the salted SHA-512 enCRYPTed password/passphrase string:'
print crypt
print
print 'Give it to your email server operator.'
